### ISSUE TITLE
Add solver functionality

### ISSUE THREAD

**Issue by JakeFDev** [victorqribeiro/bridge#2]
Let a user press a "solve" button that solves the puzzle with the least amount of moves based on the current state.

A quick google search confirms that representing the states in a a graph data structure and using breadth first search might be the best implementation for this. This might be a good start to port it over to JS? http://yongouyang.blogspot.com/2013/04/solving-farmer-wolf-goat-cabbage-riddle.html

**Comment by victorqribeiro** [comment]
Excelente suggestion. Done!
